name: Deploy Automático para Dominios.pt
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server:  94.126.169.39
        username: upload@aduc-art.pt
        password: ${{secrets.FTP_PASSWORD}}
        server-dir: public_html/
        protocol: ftp